[manifest]
version = "1.0.0"
dump_lua = true
priority = 1


    # Freezer - Ice Cream
[[patches]]
[patches.pattern]
target = "card.lua"
pattern = "if self.ability.extra.chips - self.ability.extra.chip_mod <= 0 then"
position = "at"
payload = '''if self.ability.extra.chips - self.ability.extra.chip_mod <= 0 and not Cracker.is_adjacent_to_freezer(self) then'''
match_indent = true
times = 1

    # Freezer - Turtle Bean
[[patches]]
[patches.pattern]
target = "card.lua"
pattern = "if self.ability.extra.h_size - self.ability.extra.h_mod <= 0 then"
position = "at"
payload = '''if self.ability.extra.h_size - self.ability.extra.h_mod <= 0 and not Cracker.is_adjacent_to_freezer(self) then'''
match_indent = true
times = 1

    # Freezer/Upgraded Food Joker - Popcorn
[[patches]]
[patches.pattern]
target = "card.lua"
pattern = "if self.ability.mult - self.ability.extra <= 0 then"
position = "at"
payload = '''if self.ability.mult - self.ability.extra <= 0 and not Cracker.is_adjacent_to_freezer(self) then 
G.GAME.pool_flags.popcorn_eaten = true'''
match_indent = true
times = 1

    # Freezer - Seltzer
[[patches]]
[patches.pattern]
target = "card.lua"
pattern = "if self.ability.extra - 1 <= 0 then"
position = "at"
payload = '''if self.ability.extra - 1 <= 0 and not Cracker.is_adjacent_to_freezer(self) then'''
match_indent = true
times = 1

[[patches]]
[patches.pattern]
target = "card.lua"
pattern = "self.ability.extra = self.ability.extra - 1"
position = "at"
payload = "self.ability.extra = self.ability.extra - (Cracker.is_adjacent_to_freezer(self) and 0 or 1)"
match_indent = true
times = 1

[[patches]]
[patches.pattern]
target = "card.lua"
pattern = "message = self.ability.extra..'',"
position = "at"
payload = "message = Cracker.is_adjacent_to_freezer(self) and localize('k_cracker_frozen_ex') or self.ability.extra..'',"
match_indent = true
times = 1
