[manifest]
version = "1.0.0"
dump_lua = true
priority = 1

    # Patchwork deck requires voucher override
[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = '''if v.requires then '''
position = "at"
payload = '''
if not G.GAME.modifiers.voucher_override and G.P_CENTERS[v.key] and G.P_CENTERS[v.key].discovered and G.P_CENTERS[v.key].pools and G.P_CENTERS[v.key].pools.DeckVoucher then
    include = false
elseif G.GAME.modifiers.voucher_override and not (G.P_CENTERS[v.key] and G.P_CENTERS[v.key].discovered and G.P_CENTERS[v.key].pools and G.P_CENTERS[v.key].pools.DeckVoucher) then
    include = false
elseif v.requires then
'''
match_indent = true
times = 1

[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = '''elseif _type == 'Voucher' then _pool[#_pool + 1] = "v_blank"'''
position = "at"
payload = '''
elseif _type == 'Voucher' then _pool[#_pool + 1] = ((G.GAME.modifiers.voucher_override and "v_pw_erratic") or "v_blank")
'''
match_indent = true
times = 1

[[patches]]
[patches.pattern]
target = "game.lua"
pattern = '''for _,_ in pairs(G.GAME.current_round.voucher.spawn) do vouchers_to_spawn = vouchers_to_spawn + 1 end
if vouchers_to_spawn < G.GAME.starting_params.vouchers_in_shop + (G.GAME.modifiers.extra_vouchers or 0) then
    SMODS.get_next_vouchers(G.GAME.current_round.voucher)
end
for _, key in ipairs(G.GAME.current_round.voucher or {}) do
    if G.P_CENTERS[key] and G.GAME.current_round.voucher.spawn[key] then
        SMODS.add_voucher_to_shop(key)
    end
end'''
position = "at"
payload = '''
if G.GAME.current_round.voucher and G.GAME.current_round.voucher.spawn then
    if (G.GAME.modifiers.voucher_restock_antes == nil or G.GAME.round_resets.ante % G.GAME.modifiers.voucher_restock_antes == 1) then
        for _,_ in pairs(G.GAME.current_round.voucher.spawn) do vouchers_to_spawn = vouchers_to_spawn + 1 end
        if vouchers_to_spawn < G.GAME.starting_params.vouchers_in_shop + (G.GAME.modifiers.extra_vouchers or 0) then
            SMODS.get_next_vouchers(G.GAME.current_round.voucher)
        end
    end
    for _, key in ipairs(G.GAME.current_round.voucher or {}) do
        if G.P_CENTERS[key] and G.GAME.current_round.voucher.spawn[key] then
            SMODS.add_voucher_to_shop(key)
        end
    end
end'''
match_indent = true
times = 1

[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = '''G.GAME.current_round.voucher = SMODS.get_next_vouchers()'''
position = "at"
payload = '''
if (G.GAME.modifiers.voucher_restock_antes == nil or G.GAME.round_resets.ante % G.GAME.modifiers.voucher_restock_antes == 1) then
    G.GAME.current_round.voucher = SMODS.get_next_vouchers()
end'''
match_indent = true
times = 1

[[patches]]
[patches.pattern]
target = "card.lua"
pattern = '''if self.shop_voucher then G.GAME.current_round.voucher.spawn[self.config.center_key] = false end 
if self.from_tag then G.GAME.current_round.voucher.spawn[G.GAME.current_round.voucher[1]] = false end'''
position = "at"
payload = '''
if G.GAME.current_round.voucher and G.GAME.current_round.voucher.spawn then
    if self.shop_voucher then G.GAME.current_round.voucher.spawn[self.config.center_key] = false end 
    if self.from_tag then G.GAME.current_round.voucher.spawn[G.GAME.current_round.voucher[1]] = false end
end
'''
match_indent = true
times = 1

    # patchwork plasma deck
[[patches]]
[patches.pattern]
target = "back.lua"
pattern = '''if self.name == 'Plasma Deck' and args.context == 'final_scoring_step' then'''
position = "at"
payload = '''if (self.name == 'Plasma Deck' or G.GAME.modifiers['plasma'] or G.GAME.used_vouchers['v_pw_plasma']) and args.context == 'final_scoring_step' then'''
match_indent = true
times = 1


    # patch for All In Jest patchwork deck (will need to be modified when cracker's patchwork deck gets a decksleeve)
[[patches]]
[patches.pattern]
target = "game.lua"
pattern = '''for k, v in pairs(self.ANIMATIONS) do'''
position = "before"
payload = '''
if G.GAME.modifiers.suit_patcher then
    if G then
        for k, v in pairs(G) do
            if G[k] and type(G[k]) == 'table' and G[k].cards then
                for _, cur_card in pairs(G[k].cards) do
                    if cur_card.ability and not cur_card.ability.patches and cur_card.ability.set and (cur_card.ability.set == 'Default' or cur_card.ability.set == 'Enhanced') then
                        local keys = {}
		                    for key, val in pairs(SMODS.Suits) do
                            if val.in_pool and val.in_pool(val, nil) then
                                keys[#keys+1] = key
                            elseif not val.in_pool then
			                          keys[#keys+1] = key
                            end
		                    end
		                    local cur_suit = pseudorandom_element(keys, pseudoseed('patchwork'))
                        local temp_index = 0
                        while cur_suit == cur_card.base.suit do
                            cur_suit = pseudorandom_element(keys, pseudoseed('patchwork_resample'..temp_index))
                            temp_index = temp_index + 1
                        end
			                  All_in_Jest.add_patch(cur_card, cur_suit, true);
                    end
                end
            end
        end
    end
end
'''
match_indent = true
times = 1
