[manifest]
version = "1.0.0"
dump_lua = true
priority = 1

    # Buttered Popcorn
[[patches]]
[patches.pattern]
target = "game.lua"
pattern = '''j_popcorn=          {order = 97,   unlocked = true, discovered = false, blueprint_compat = true, perishable_compat = true, eternal_compat = false, rarity = 1, cost = 5, name = "Popcorn",set = "Joker", config = {mult = 20, extra = 4}, pos = {x=1,y=15}},'''
position = "at"
payload = '''
j_popcorn=          {order = 97,   unlocked = true, discovered = false, blueprint_compat = true, perishable_compat = true, eternal_compat = false, rarity = 1, cost = 5, name = "Popcorn",set = "Joker", config = {mult = 20, extra = 4}, pos = {x=1,y=15}, no_pool_flag = 'popcorn_eaten'},
'''
match_indent = true
times = 1
