[manifest]
version = "1.0.0"
dump_lua = true
priority = 1

    # Cavendish
[[patches]]
[patches.pattern]
target = "card.lua"
pattern = "if self.ability.name == 'Gros Michel' then G.GAME.pool_flags.gros_michel_extinct = true end"
position = "at"
payload = '''
if self.ability.name == 'Gros Michel' then G.GAME.pool_flags.gros_michel_extinct = true
elseif self.ability.name == 'Cavendish' and not CrackerConfig.disable_upgradedfood then G.GAME.pool_flags.cavendish_extinct = true
end
'''
match_indent = true
times = 1

[[patches]]
[patches.pattern]
target = "game.lua"
pattern = '''j_cavendish=        {order = 61,  unlocked = true, discovered = false, blueprint_compat = true, perishable_compat = true, eternal_compat = false, rarity = 1, cost = 4, name = "Cavendish", pos = {x=5,y=11}, set = "Joker", cost_mult = 1.0, config = {extra = {odds = 1000, Xmult = 3}}, yes_pool_flag = 'gros_michel_extinct'},'''
position = "at"
payload = '''j_cavendish=        {order = 61,  unlocked = true, discovered = false, blueprint_compat = true, perishable_compat = true, eternal_compat = false, rarity = 1, cost = 4, name = "Cavendish", pos = {x=5,y=11}, set = "Joker", cost_mult = 1.0, config = {extra = {odds = 1000, Xmult = 3}}, yes_pool_flag = 'gros_michel_extinct', no_pool_flag = 'cavendish_extinct'},'''
match_indent = true
times = 1

    # Buttered Popcorn
[[patches]]
[patches.pattern]
target = "card.lua"
pattern = '''if self.ability.name == 'Popcorn' and not context.blueprint then
if self.ability.mult - self.ability.extra <= 0 then '''
position = "after"
payload = '''
if not CrackerConfig.disable_upgradedfood then
    G.GAME.pool_flags.popcorn_eaten = true
end
'''
match_indent = true
times = 1

[[patches]]
[patches.pattern]
target = "game.lua"
pattern = '''j_popcorn=          {order = 97,   unlocked = true, discovered = false, blueprint_compat = true, perishable_compat = true, eternal_compat = false, rarity = 1, cost = 5, name = "Popcorn",set = "Joker", config = {mult = 20, extra = 4}, pos = {x=1,y=15}},'''
position = "at"
payload = '''
j_popcorn=          {order = 97,   unlocked = true, discovered = false, blueprint_compat = true, perishable_compat = true, eternal_compat = false, rarity = 1, cost = 5, name = "Popcorn",set = "Joker", config = {mult = 20, extra = 4}, pos = {x=1,y=15}, no_pool_flag = 'popcorn_eaten'},
'''
match_indent = true
times = 1

    # Frozen Custard
[[patches]]
[patches.pattern]
target = "card.lua"
pattern = '''if self.ability.name == 'Ice Cream' and not context.blueprint then
if self.ability.extra.chips - self.ability.extra.chip_mod <= 0 then '''
position = "after"
payload = '''
if not CrackerConfig.disable_upgradedfood then
    G.GAME.pool_flags.ice_cream_eaten = true
end
'''
match_indent = true
times = 1

[[patches]]
[patches.pattern]
target = "game.lua"
pattern = '''j_ice_cream=        {order = 50,  unlocked = true,  discovered = false, blueprint_compat = true, perishable_compat = true, eternal_compat = false, rarity = 1, cost = 5, name = 'Ice Cream', pos = {x = 4, y = 10}, set = 'Joker', config = {extra = {chips = 100, chip_mod = 5}}},'''
position = "at"
payload = '''
j_ice_cream=        {order = 50,  unlocked = true,  discovered = false, blueprint_compat = true, perishable_compat = true, eternal_compat = false, rarity = 1, cost = 5, name = 'Ice Cream', pos = {x = 4, y = 10}, set = 'Joker', config = {extra = {chips = 100, chip_mod = 5}}, no_pool_flag = 'ice_cream_eaten'},
'''
match_indent = true
times = 1


    # Hard Seltzer
[[patches]]
[patches.pattern]
target = "card.lua"
pattern = '''if self.ability.name == 'Seltzer' and not context.blueprint then
if self.ability.extra - 1 <= 0 then '''
position = "after"
payload = '''
if not CrackerConfig.disable_upgradedfood then
    G.GAME.pool_flags.seltzer_drank = true
end
'''
match_indent = true
times = 1

[[patches]]
[patches.pattern]
target = "game.lua"
pattern = '''j_selzer=           {order = 102,  unlocked = true, discovered = false, blueprint_compat = true, perishable_compat = true, eternal_compat = false, rarity = 2, cost = 6, name = "Seltzer",set = "Joker", config = {extra = 10}, pos = {x=3,y=15}},'''
position = "at"
payload = '''
j_selzer=           {order = 102,  unlocked = true, discovered = false, blueprint_compat = true, perishable_compat = true, eternal_compat = false, rarity = 2, cost = 6, name = "Seltzer",set = "Joker", config = {extra = 10}, pos = {x=3,y=15}, no_pool_flag='seltzer_drank'},
'''
match_indent = true
times = 1


    # Turtle Bean
[[patches]]
[patches.pattern]
target = "card.lua"
pattern = '''if self.ability.name == 'Turtle Bean' and not context.blueprint then
if self.ability.extra.h_size - self.ability.extra.h_mod <= 0 then '''
position = "after"
payload = '''
if not CrackerConfig.disable_upgradedfood then
    G.GAME.pool_flags.turtle_bean_eaten = true
end
'''
match_indent = true
times = 1

[[patches]]
[patches.pattern]
target = "game.lua"
pattern = '''j_turtle_bean=      {order = 80,  unlocked = true,  discovered = false, blueprint_compat = false, perishable_compat = true, eternal_compat = false, rarity = 2, cost = 6, name = "Turtle Bean",set = "Joker", config = {extra = {h_size = 5, h_mod = 1}}, pos = {x=4,y=13}},'''
position = "at"
payload = '''
j_turtle_bean=      {order = 80,  unlocked = true,  discovered = false, blueprint_compat = false, perishable_compat = true, eternal_compat = false, rarity = 2, cost = 6, name = "Turtle Bean",set = "Joker", config = {extra = {h_size = 5, h_mod = 1}}, pos = {x=4,y=13}, no_pool_flag='turtle_bean_eaten'},
'''
match_indent = true
times = 1


    # Tsukemen
[[patches]]
[patches.pattern]
target = "card.lua"
pattern = '''if self.ability.name == 'Ramen' and not context.blueprint then
if self.ability.x_mult - self.ability.extra <= 1 then '''
position = "after"
payload = '''
if not CrackerConfig.disable_upgradedfood then
    G.GAME.pool_flags.ramen_eaten = true
end
'''
match_indent = true
times = 1

[[patches]]
[patches.pattern]
target = "game.lua"
pattern = '''j_ramen=            {order = 100,  unlocked = true, discovered = false, blueprint_compat = true, perishable_compat = true, eternal_compat = false, rarity = 2, cost = 6, name = "Ramen",set = "Joker", config = {Xmult = 2, extra = 0.01}, pos = {x=2,y=15}},'''
position = "at"
payload = '''
j_ramen=            {order = 100,  unlocked = true, discovered = false, blueprint_compat = true, perishable_compat = true, eternal_compat = false, rarity = 2, cost = 6, name = "Ramen",set = "Joker", config = {Xmult = 2, extra = 0.01}, pos = {x=2,y=15}, no_pool_flag = 'ramen_eaten'},
'''
match_indent = true
times = 1